apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  type: Opaque
  data:
    username: 'robot$robot_k8s_learn'
    password: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njk4MTI3MzAsImlhdCI6MTY2NzIyMDczMCwiaXNzIjoiaGFyYm9yLXRva2VuLWRlZmF1bHRJc3N1ZXIiLCJpZCI6MiwicGlkIjoyLCJhY2Nlc3MiOlt7IlJlc291cmNlIjoiL3Byb2plY3QvMi9yZXBvc2l0b3J5IiwiQWN0aW9uIjoicHVzaCIsIkVmZmVjdCI6IiJ9XX0.iOpE_8koIb9WZrpj6hVxZOhHXABZYKTZ0vNlcQSgfc4cFQ-wZdBZsxCpAKPNgqQQmU73wxrAx7nTCIH8QmBqvKw6HvO67m49KvIeHCI907FZVdDWONpoh51BS0K98JUeK_2PEJ9dSE1BEOxTG3A7Zzjif794H4j8KY36fuc_RXKtjy49LKS7m9ZTLtvKv6h3jhIGIJqY9smxhg2x5kKQ5Tpal_rGynBHB6d8TY9ImxxDgLzdiT1WFSPEYbKyJFWWK-GtP_83fsQJVRxNmQTxLTAVpp53dRwpC2HZjdwVFn-0T8fsLorJgoPNcSOMpKRay_8j4RmWsaAuea-xh8Lum8mnUnyvizGAoRqq55bh0HjbhZcD2bjgnvAo1BgBaQ31exOz1_EbOBallKX9kKawOJWec7r0kWPugXNPULe-XzKR7MsIo7Wj-Q6WATwrP1ZFwC9fFVoiDLFFfJFwVKwdoqSaueOBPz2iL7VNsds9KR_TeQJg2UFwShhKMCmvN7avjNgugbuexyNBJQnFIoCdaPEzAOgbNjxcwN-LwEq-cQk2p_3iGNONKbYHfcRB-DnqNZSApeHIDIt0qspTAoySC6f2NBJOwhXvNNYZWNksnU6sL7Ix7JE4WkdiRi8ia1L28h5ct6qZUjfT-p0EGc4QY5EoD1vs8J1wBoD_UqB_kt8'
