apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.name: nginx-deploy
  template:
    metadata:
      labels:
        app.name: nginx-deploy
    spec:
      containers:
      - image: nginx:1.21.1
        imagePullPolicy: IfNotPresent
        name: nginx-deploy
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-nodeport
  labels:
    app: nginx-svc-nodeport
spec:
  type: NodePort  # Service 类型指定为NodePort,其它如ExternalName,ClusterIP,LoadBalancer
  ports:
  - port: 80      # Service 在集群内部的服务端口                      
    targetPort: 80 # 关联pod对外开放的端口
    nodePort: 31080 # 集群外访问端口，范围为：30000-32767
  selector:
    app.name: nginx-deploy    # 关联pod的标签
