apiVersion: v1
kind: Service
metadata:
  name: svc-tomcat
  labels:
    app: web
    type: backend
    version: v2
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30012
  selector:
    app: web