apiVersion: v1
kind: Pod
metadata:
  name: liveness-prob
  labels:
    version: test
    type: web
spec:
  imagePullSecrets: 
  - name: harbor-pull-secret # 使用harbor机器人账号创建
  containers:
  - name: liveness-test
    image: harbor.xiejiawen.cn/k8s-learn/busybox-base:v1
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
