apiVersion: v1
kind: Pod
metadata:
  name: liveness-prob-tcpsocket
  labels:
    version: test
    type: web
spec:
  imagePullSecrets: 
  - name: harbor-pull-secret # 使用harbor机器人账号创建
  containers:
  - name: liveness-test
    image: harbor.xiejiawen.cn/k8s-learn/tomcat9-jdk9-base:v1
    ports:
    - containerPort: 8080
    volumeMounts:  
    - name: web-data-beta
      mountPath: /usr/local/apache-tomcat-9.0.68/webapps
    livenessProbe:
      tcpSocket:
        port: 8081 # 诊断时会连容器的8081端口，如果此端口不在，诊断失败
      initialDelaySeconds: 3
      periodSeconds: 3      
  volumes:
  - name: web-data-beta
    nfs:
      server: nfs-server.xiejiawen.cn
      path: /data/tomcat/beta/web/webapps
      #readOnly: true
