apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-tomcat2
  labels: 
    app: web
    type: backend
    version: prod
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      version: prod
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata: 
      name: tomcat-prod
      labels:
        app: web
        type: backend
        version: prod
    spec:
      imagePullSecrets: 
      - name: arbor-robot-secret # 使用harbor机器人账号创建
      containers:
      - name: tomcat-container-prod
        image: harbor.xiejiawen.cn/k8s-learn/tomcat9-jdk9-base:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: web-data-prod
          mountPath: /usr/local/apache-tomcat-9.0.68/webapps
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: web-data-prod
        nfs:
          server: nfs-server.xiejiawen.cn
          path: /data/tomcat/prod/web/webapps
          #readOnly: true


