apiVersion: v1
kind: Secret
metadata:
  name: harbor-pull-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IueGllamlhd2VuLmNuIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NmVYQXpWVXRvZDIweE1reGhiVzFxUmpnPSIKCQl9Cgl9Cn0=
