apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-tomcat
  labels: 
    app: web
    type: backend
    version: beta
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata: 
      name: tomcat-test
      labels:
        app: web
        type: backend
    spec:
      imagePullSecrets: 
      - name: harbor-pull-secret # 使用harbor机器人账号创建
      containers:
      - name: tomcat-container
        image: harbor.xiejiawen.cn/k8s-learn/tomcat9-jdk9-base:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
        - name: web-data-beta
          mountPath: /usr/local/apache-tomcat-9.0.68/webapps
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: web-data-beta
        nfs:
          server: nfs-server.xiejiawen.cn
          path: /data/tomcat/beta/web/webapps
          #readOnly: true
